### ISSUE TITLE
If init failed, then all mapping in container wont work

### ISSUE THREAD

**Issue by neoremind** [neoremind/easy-mapper#6]
The exception looks like:
```
2017-07-01 00:02:51.338 | ERROR in c.h.a.a.e.e.AbstractExceptionMapper.toResponse(25) [|Jetty-Server-67] els-ass-160 user_id= hulu_request_id=a3441bf4-2996-443c-a561-1a90dc2fdaef path=GET_deletion_uid - Generating mapping code failed for ClassMap([A]:DeletionUid, [B]:DeletionUidDto), this should not happen, probably the framework could not handle mapping correctly based on your bean [java]  [els-ass-160]
com.baidu.unbiz.easymapper.exception.MappingException: Generating mapping code failed for ClassMap([A]:DeletionUid, [B]:DeletionUidDto), this should not happen, probably the framework could not handle mapping correctly based on your bean [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:169) ~[app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:116) ~[app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.ClassMapBuilder.registerAndMap(ClassMapBuilder.java:241) ~[app.jar:na] [java]  [els-ass-160]
        at com.hulu.ap.meta.api.DeletionUidApi$1.apply(DeletionUidApi.java:119) ~[app.jar:na] [java]  [els-ass-160]
        at com.hulu.ap.meta.api.DeletionUidApi$1.apply(DeletionUidApi.java:115) ~[app.jar:na] [java]  [els-ass-160]
        at com.hulu.ap.meta.api.DeletionUidApi.getLatest(DeletionUidApi.java:80) ~[app.jar:na] [java]  [els-ass-160]
```
and it keeps occurring if the following exception happens when application startup.
```
2017-07-01 00:02:51.141 | ERROR in c.b.u.e.codegen.MappingCodeGenerator.build(79) [|Jetty-Server-67] els-ass-160 user_id= hulu_request_id=a3441bf4-2996-443c-a561-1a90dc2fdaef path=GET_deletion_uid - Generating mapping code with error: null [java]  [els-ass-160]
java.util.NoSuchElementException: null [java]  [els-ass-160]
        at sun.misc.CompoundEnumeration.nextElement(CompoundEnumeration.java:59) ~[na:1.8.0_92] [java]  [els-ass-160]
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357) ~[na:1.8.0_92] [java]  [els-ass-160]
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393) ~[na:1.8.0_92] [java]  [els-ass-160]
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474) ~[na:1.8.0_92] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.mapping.DefaultMappingStrategy.generateMappingCode(DefaultMappingStrategy.java:43) ~[app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.codegen.MappingCodeGenerator.generateMappingCode(MappingCodeGenerator.java:141) ~[app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.codegen.MappingCodeGenerator.addMapMethod(MappingCodeGenerator.java:106) ~[app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.codegen.MappingCodeGenerator.build(MappingCodeGenerator.java:68) ~[app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.CopyByRefMapper$2.compute(CopyByRefMapper.java:165) [app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.CopyByRefMapper$2.compute(CopyByRefMapper.java:162) [app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.util.Memoizer$1.call(Memoizer.java:67) [app.jar:na] [java]  [els-ass-160]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_92] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.util.Memoizer.compute(Memoizer.java:73) [app.jar:na] [java]  [els-ass-160]
        at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:160) [app.jar:na] [java]  [els-ass-160]
```

**Comment by neoremind** [comment]
fixed, will be used in production env to check it out
