### ISSUE TITLE
容器启动时，偶尔会报错，重启可能会解决问题

### ISSUE THREAD

**Issue by drtrang** [neoremind/easy-mapper#8]
我创建了一个静态的 Mapper 对象，然后在其它地方使用该对象，看起来似乎没问题，但是在外部容器启动时，项目偶尔会报错，而且错误会一直持续，只能重启，请帮忙看看是什么原因？这个问题很久之前就有，一直没有找到原因，看更新日志 **1.0.3** 版本貌似解决了，但是我更新后还是会报错……
```
private static final Mapper mapper = MapperFactory.getCopyByRefMapper().mapClass(Prospect.class, ProspectVo.class).register();
mapper.map(source, ProspectVo.class);
```
```
Caused by: com.baidu.unbiz.easymapper.exception.MappingException: No class map found for (String, String), make sure type or nested type is registered beforehand
	at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:157)
	at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:116)
	at com.baidu.unbiz.generated.EasyMapper_Prospect_TO_ProspectVo_Mapper63926513617948576$0.map(EasyMapper_Prospect_TO_ProspectVo_Mapper63926513617948576$0.java)
	at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:176)
	at com.baidu.unbiz.easymapper.CopyByRefMapper.map(CopyByRefMapper.java:116)
	at com.github.trang.copiers.mapper.MapperCopier.copy(MapperCopier.java:40)
	... 156 common frames omitted
```

**Comment by drtrang** [comment]
我在开发环境没有复现，线上也是偶尔会在容器启动时报错，一旦报错就会持续下去，请帮忙看看是我使用的原因还是 EasyMapper 的问题，谢谢。

**Comment by neoremind** [comment]
my fault, 我在我们的生产环境上发现了问题是，JAVA SPI service loader不是线程安全的，所以当容器启动的时候有很多pending calls并发执行，就会造成问题，之前1.0.3是为了修复这个问题，但是明显没有避免成功。my fault，sorry for issue，目前你有两种workround。

1. 回滚到1.0.2，但是还是会有风险。
2. 保持1.0.3版本，在容器启动的时候，比如spring mvc，在lifecycle中加入以下逻辑（例如init或者post construct bean），这样就可以单线程初始化完毕。
```
ServiceLoaderHelper.getInstance();
MapperFactory.getCopyByRefMapper();
```

我还在想一个更加clean、green的solution，避免hardcode初始化逻辑。非常抱歉带来的不便。

**Comment by neoremind** [comment]
一旦初始化失败，easy mapper缓存的mapping就会state混乱，所以总是报错。

**Comment by drtrang** [comment]
感谢回复，参考第二种方法，我在 Spring 的 ContextLoaderListener 中增加了初始化 ServiceLoaderHelper 的代码，希望可以解决问题，有后续进展我会及时回复。
```java
public class CustomContextLoaderListener extends ContextLoaderListener {
    static {
        ServiceLoaderHelper.getInstance();
    }
}
```

**Comment by ilovejiaozi** [comment]
在尝试用第二种方法解决。

ps: 对于spi 可以不用ServiceLoader，而是像dubbo一样实现一个ExtensionLoader来进行加载。不过稍微占点内存，你觉得如何？

**Comment by neoremind** [comment]
@ilovejiaozi 非常同意，对于模块化可以自己做实现，后续可以考虑，如果你有idea，欢迎提PR。

**Comment by neoremind** [comment]
@ilovejiaozi @drtrang I have added how-to section in readme to deal with such problem. https://github.com/neoremind/easy-mapper#4-initialization
